title: Anuj Gajjar # your name (or website title) here
logo: "/images/Anuj-Gajjar_copy_copy.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br> 
  About Me
  <br><br>
  I am Anuj Gajjar, a second year Computer and Electrical Engineering major, with a Computer Science minor at Northeastern; 
  currently trying to obtain a breadth of knowledge in computing and electronics systems; with current experience 
  in embedded design, electronics design, signal processing, image processing, and algorithm design; 
  with programming experience in C++, Java, MATLAB, Arduino, and Python.
  
  Currently at Northeastern, I am a part of Generate Product Development and the Optical Science Laboratory.
  I love my work at both places, Generate allows me to practice a wide amount of my knowledge, while optics allows me
  to get some depth in a field and utilize a wide variety of theory.
  
  Outside of engineering, I have played the guitar and saxophone for 10 years, I enjoy taking out my camera here and then, 
  occasionally play a board game, go out on a walk here and then, love BoJack Horseman, or may be in India.

  I hope that through my experiences and engineering skills that I am able to make some form of positive impact, 
  wheter or not it is internal in an organization, within STEM communities, or improves someone's life.
  <br><br>
  <a href="https://www.linkedin.com/in/anuj-gajjar-b2b16a189/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
