title: Anuj Gajjar # your name (or website title) here
logo: "/images/Anuj-Gajjar_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)  
  <br>
  <a href="https://www.linkedin.com/in/anuj-gajjar/">My LinkedIn Profile</a> 
  
  <br>
  <a href="https://github.com/gajjara/">My Github Profile</a>
  
  <br>
  Email: gajjar.a@husky.neu.edu <br>
  Phone: 857-225-4456
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
