title: Anuj Gajjar # your name (or website title) here
logo: "/images/Anuj-Gajjar_copy_copy.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am a second year Computer and Electrical Engineering major, with a CS minor at Northeastern; 
  to obtain a breadth of knowledge in computing and electronics systems.
  
  I play the guitar and saxophone, take out my camera here and then, 
  occasionally pick up a board game, go out on a walk, or in India.
  
  I hope that through my experience that I can make some form of positive impact.
  <br><br>
  <a href="https://www.linkedin.com/in/anuj-gajjar-b2b16a189/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
